### ISSUE TITLE
Updade to 1.7.7

### ISSUE THREAD

**Issue by net32** [sillerud/BungeeCord#18]
hey, updade the project for compatibility with 1.7.8 :smile:

**Comment by Katelyn-SN** [comment]
That likely will never happen as that would requiring 3 protocols side by side when 2 is complicated enough already.

**Comment by literalplus** [comment]
Vanilla Bungee has it and supporting 1.7.2 and 1.7.(9 now) is just a few lines, if I remember correctly.
-- This message was sent from my tablet. Check my homepage!

**Comment by suchtie664** [comment]
Is it possible with this code?
https://github.com/SpigotMC/BungeeCord/commit/cd518690fd692350c40e93e9c1c57d6e50f8e79e
and
https://github.com/SpigotMC/BungeeCord/commit/1d3adc53170b5da41852a513ba413dbd3e57c7ec
Correct me if I wrong.

**Comment by literalplus** [comment]
Yes, that's what I was referring to.

(Might make a PR once I get time)

**Comment by Katelyn-SN** [comment]
You guys don't understand how it works you can't just drop these patches into this version of bungee as the protocol hack that this version uses is heavily modified nothing that you think will work with it will not. Since this system requires to run 2 different protocol systems side by side.

**Comment by literalplus** [comment]
I understand that it is not possible to throw in these patches 1:1, but I think you see that it is possible to support 1.7.9 too with little effort. (Or medium, if you want)
(For example, we'd need to have the uuid methods on players too)

**Comment by Katelyn-SN** [comment]
Its not as easy as you may think i did the patch already and it works and allows clients to connect but there is constant issues with it having to understand packets likely due to uuid name changes

**Comment by net32** [comment]
I did the code to adapt the UUID of version 1.7.6, but 1.6.4 Spigot is unsuitable for UUID when a player is in the same chunk that another conflict showing that the UUID is invalid UUID.

**Comment by Katelyn-SN** [comment]
Would you mind sharing the code so we can maybe work out a solution

**Comment by net32** [comment]
I will make a fork

**Comment by Sin96** [comment]
i got a workin BungeeCord, which allows to join with 1.7.6+ on a 1.6.4 Spigot server. I have only one problem anymore. A 1.7.6+ Client doesn't load the skins.. so you cannot see a new spawned player for about 20-30 seconds. After that the client sets a standard skin. Do you have any ideas to fix that?

**Comment by Katelyn-SN** [comment]
Thats a very simple patch and was done by md_5 weeks ago https://github.com/SpigotMC/BungeeCord/commit/1d3adc53170b5da41852a513ba413dbd3e57c7ec

Also please share your code we are eager to get our servers working as right now we are having to redirect users with direct ips

**Comment by Katelyn-SN** [comment]
Also @net32 the fork is not very helpful if you don't commit your changes to it :P

**Comment by net32** [comment]
@tf101-wizard hey, look at my fork: https://github.com/net32/BungeeCord
the error of a player being in the same chunk that other still persists only in version 1.7.6: http://prntscr.com/3beiv4

**Comment by Katelyn-SN** [comment]
Give me a minute mine worked all I did was change protocol mapping from 4-5
with no issues haha worst method but it worked

**Comment by Katelyn-SN** [comment]
Looks like you didn't isolate use of uuid for that client so basicly its looking for the uuid of the 1.6 player and cannot find it

**Comment by net32** [comment]
not yet understood why the error only occurs when two players are in the same chunk

**Comment by Katelyn-SN** [comment]
1.6.4 clients use the name system when 1.7.6+ clients use uuid support see if the error occurs with just changing the 4 to a 5 in packet mapping also send me your bungee and server logs so I can see why your uuid changes are causing that issue

**Comment by net32** [comment]
I'm almost giving up, I think I'll upgrade everything to 1.7  ):

**Comment by Katelyn-SN** [comment]
We can get it just get me those things I asked for

**Comment by net32** [comment]
make a clone of my fork and compile, the problem is only with the protocol 5, if you can get into my test server: 177.96.42.249

**Comment by Katelyn-SN** [comment]
No PC ATM u will have to do that on the long ride home from a small camping trip 1-2 hours I'll be around with a PC to help add my Skype kevhawk2914 so we can elaborate

**Comment by Sn0wStorm** [comment]
I have made a version that is fully working with the new Protocol, only drawback: Fake Players (NPCs) have no skin on Protocol 5. This is due to how the Skinsystem changed.

You are getting the Client Error, because you are not rewriting the Spawn Player Packet (The current rewrite just adds wowe_such_packet as UUID)

Its a rather hacky way to determine which protocol to rewrite the Spawn Player Packet to, but it works. I still have to clean up the code, remove Debug stuff, do testing and I have almost no time over the next days, so it may take a while.

**Comment by Sin96** [comment]
can u upload it? maybe i can fix that spawn player problem

**Comment by Sn0wStorm** [comment]
Well as said its fully working except NPC Skins. Sadly I have no time to fork and upload it right now.

**Comment by suchtie664** [comment]
can somebody fix @net32 problem?

**Comment by Katelyn-SN** [comment]
Well that is essentially what Sn0wStorm is trying to fix can you possibly upload your source to dropbox @Sn0wStorm so i can get it done for these guys and if you can a diff :)

**Comment by net32** [comment]
@tf101-wizard @Sn0wStorm @suchtie664 @Sin96 : Solved: https://github.com/TheUnnamedDude/BungeeCord/pull/20

**Comment by Sn0wStorm** [comment]
Sorry that I could not upload this earlier:

https://github.com/Sn0wStorm/BungeeCord

This is my fork of it, I will not create a Pull Request as of now, because the code ist not cleaned.

**Comment by Sn0wStorm** [comment]
There is still a Problem with Player Heads in 1.7.6 +  
If a Player Head with Skin is within visible range, the Client crashes completely. Its no Packet related disconnect but a full crash. Does somebody know a solution to this problem? To reproduce you can give yourself a player head with skin with this command:  /give name 397:3 1 player:name

**Comment by floh22** [comment]
well it seems like the fork @Sn0wStorm made still works with 1.7.10 though there weren't any major changes to its not very suprising ^^ Still very awesome fork :)

**Comment by net32** [comment]
yes, but still have the problem of head

**Comment by Koya07** [comment]
Since I cannot speak English, I have translated. 

only 1.7.7,it is made into the head of Steve. 
I can not good programming.

**Comment by Sn0wStorm** [comment]
I am working on a solution for the Problem with the heads.

But it will not have any skin, so every head will be Steve for the new versions.

**Comment by Sn0wStorm** [comment]
Fixed here: https://github.com/Sn0wStorm/BungeeCord/commit/224b9ecc68f2e313e852d4528270a23b2fc8d9b1

Skinned Heads will not show skins for the newer versions (1.7.10) much like NPCs.

---

If somebody wants to try to make skins show correctly on heads and NPCs, take a look at how Citizens2 fetches Skins here: https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/npc/entity/HumanController.java  
How the Skin NBT-Data has changed: Bottom of the Page here, under Skull, the whole Owner Tag-Compound would need to be created: http://minecraft.gamepedia.com/Chunk_format#Tile_Entity_Format

**Comment by Koya07** [comment]
If https://github.com/Sn0 wStorm/BungeeCord is Build and it tries to go into a server, an error will come out. 

io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks
Warning: A task raised an exception.
java.lang.NullPointerException
    at net.md_5.bungee.connection.InitialHandler$8$1.run(InitialHandler.java:513)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Unknown Source)

**Comment by Koya07** [comment]
An error will be made if Offlinemode=false is used. 

io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks
Warning: A task raised an exception.
java.lang.NullPointerException
at net.md_5.bungee.connection.InitialHandler$8$1.run(InitialHandler.java:513)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
at java.lang.Thread.run(Unknown Source)

**Comment by Sn0wStorm** [comment]
Hm, i did not test offline-mode

**Comment by Koya07** [comment]
I want to add, if possible the offline mode
